# NOTE: Mock values added here for helm linter to pass. Actual values are set in main.tf
licensing_subscription_channel: v4.2
licensing_catalog_source_image: icr.io/cpopen/ibm-licensing-catalog@sha256:ce7e935049eaab440d1e24bf212aec55cedf3585d3a71eb3dcf648c5b1c4b74f
licensing_namespace: ibm-licensing
licensing_catalog: ibm-licensing-catalog
licensing_operator: ibm-licensing-operator-app
licensing_operator_group: licensing-operatorgroup
openshift_source: openshift-marketplace
