# NOTE: Mock values added here for helm linter to pass. Actual values are set in main.tf
licensing_subscription_channel: v4.2
licensing_catalog_source_image: icr.io/cpopen/ibm-licensing-catalog@sha256:8e2bee469a186599167283316e29f9e6e4f413b7bc7cdebcd3828ecf8f81b956
licensing_namespace: ibm-licensing
licensing_catalog: ibm-licensing-catalog
licensing_operator: ibm-licensing-operator-app
licensing_operator_group: licensing-operatorgroup
openshift_source: openshift-marketplace
