apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cert_manager_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.cert_manager_catalog }}
  namespace: {{ .Values.openshift_source }}
spec:
  displayName: IBM Cert Manager Catalog
  publisher: IBM
  sourceType: grpc
  image: {{ .Values.cert_manager_catalog_source_image }}
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: {{ .Values.cert_manager_operator_group }}
  namespace: {{ .Values.cert_manager_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.cert_manager_operator }}
  namespace: {{ .Values.cert_manager_namespace }}
spec:
  channel: {{ .Values.cert_manager_subscription_channel }}
  installPlanApproval: Automatic
  name: {{ .Values.cert_manager_operator }}
  source: {{ .Values.cert_manager_catalog }}
  sourceNamespace: {{ .Values.openshift_source }}
