apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cert_manager_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.2.3
  publisher: IBM
  sourceType: grpc
  image: {{ .Values.cert_manager_catalog_source_image }}
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: cert-manager-operatorgroup
  namespace: {{ .Values.cert_manager_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cert-manager-operator
  namespace: {{ .Values.cert_manager_namespace }}
spec:
  channel: {{ .Values.cert_manager_subscription_channel }}
  installPlanApproval: Automatic
  name: ibm-cert-manager-operator
  source: ibm-cert-manager-catalog
  sourceNamespace: openshift-marketplace
