apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.licensing_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-licensing-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM License Service Catalog
  publisher: IBM
  sourceType: grpc
  image: {{ .Values.licensing_catalog_source_image }}
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: licensing-operatorgroup
  namespace: {{ .Values.licensing_namespace }}
spec:
  targetNamespaces:
  - ibm-licensing

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-licensing-operator-app
  namespace: {{ .Values.licensing_namespace }}
spec:
  channel: {{ .Values.licensing_subscription_channel }}
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: ibm-licensing-catalog
  sourceNamespace: openshift-marketplace
