apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.licensing_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.licensing_catalog }}
  namespace: {{ .Values.openshift_source }}
spec:
  displayName: IBM License Service Catalog
  publisher: IBM
  sourceType: grpc
  image: {{ .Values.licensing_catalog_source_image }}
  updateStrategy:
    registryPoll:
      interval: 45m

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.licensing_operator_group }}
  namespace: {{ .Values.licensing_namespace }}
spec:
  targetNamespaces:
  - {{ .Values.licensing_namespace }}

---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.licensing_operator }}
  namespace: {{ .Values.licensing_namespace }}
spec:
  channel: {{ .Values.licensing_subscription_channel }}
  installPlanApproval: Automatic
  name: {{ .Values.licensing_operator }}
  source: {{ .Values.licensing_catalog }}
  sourceNamespace: {{ .Values.openshift_source }}
